export const CREATING_REPORT = "CREATING_REPORT";

export const CREATE_REPORT_SUCCESS = "CREATE_REPORT_SUCCESS";

export const CREATE_REPORT_ERROR = "CREATE_REPORT_ERROR";

export const REPORTS_SUMMARY_SUCCESS = "REPORTS_SUMMARY_SUCCESS";

export const REPORTS_SUMMARY_FAILURE = "REPORTS_SUMMARY_FAILURE";

export const REPORT_SUMMARY_LOADING = "REPORT_SUMMARY_LOADING";

export const REPORT_CREATE_PROGRESS = "REPORT_CREATE_PROGRESS";

export const REPORT_RECORD_NOTFOUND = 'REPORT_RECORD_NOTFOUND';

